In [1]:
import os
import re
import pandas as pd
import altair as alt
import numpy as np
os.chdir('/home/jupyter/COGS 402/AI_Semiconductor_Project')

# Topic: AI Semiconductors

## Dataset 1: USGS – Commodity Statistics and Information

### 1. Silicon

In [2]:
silicon_df = pd.read_excel('data/raw/dataset1/myb1-2023-simet-ERT_0.xlsx', sheet_name = 'T8', header = None)
silicon_df.to_csv('data/raw/dataset1/silicon_T8.csv', index = False)
print(f"dataset shape: {silicon_df.shape}")
silicon_df.info()

dataset shape: (75, 12)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       73 non-null     object
 1   1       0 non-null      float64
 2   2       45 non-null     object
 3   3       3 non-null      object
 4   4       45 non-null     object
 5   5       7 non-null      object
 6   6       45 non-null     object
 7   7       11 non-null     object
 8   8       45 non-null     object
 9   9       21 non-null     object
 10  10      45 non-null     object
 11  11      14 non-null     object
dtypes: float64(1), object(11)
memory usage: 7.2+ KB

In [3]:
year_cols = [
    'production_2019_metric_tons',
    'production_2020_metric_tons',
    'production_2021_metric_tons',
    'production_2022_metric_tons',
    'production_2023_metric_tons'
]

silicon_clean = silicon_df.iloc[6:58].reset_index(drop = True)
silicon_clean = silicon_clean[[0, 2, 4, 6, 8, 10]].copy()
silicon_clean.columns = ['country'] + year_cols

silicon_clean['country'] = silicon_clean['country'].str.strip().str.rstrip(':').str.strip()
silicon_clean['material'] = silicon_clean['country'].str.extract(r'(ferrosilicon|silicon metal)', flags = re.IGNORECASE)[0].str.title()
silicon_clean['country'] = silicon_clean['country'].str.replace(r',?\s*(ferrosilicon|silicon metal).*', '', regex = True, flags = re.IGNORECASE).str.strip()
silicon_clean['country'] = silicon_clean['country'].replace('', None).ffill()
silicon_clean['material'] = silicon_clean['material'].ffill()

silicon_clean[year_cols] = silicon_clean[year_cols].apply(pd.to_numeric, errors = 'coerce')
silicon_clean = silicon_clean.dropna(subset = year_cols, how = 'all').reset_index(drop = True)
silicon_clean = silicon_clean[['country', 'material'] + year_cols]

silicon_clean.to_csv('data/processed/dataset1/silicon_production_by_country.csv', index = False)
print(f"dataset shape: {silicon_clean.shape}")
silicon_clean.sample(5)

dataset shape: (40, 7)

,country,material,production_2019_metric_tons,production_2020_metric_tons,production_2021_metric_tons,production_2022_metric_tons,production_2023_metric_tons
17,India,Ferrosilicon,93000.0,90000.0,90000.0,90000.0,90000.0
12,France,Ferrosilicon,48000.0,41000.0,44000.0,38000.0,36000.0
39,"United States, total silicon materials8",Ferrosilicon,419000.0,NaN,NaN,NaN,NaN
19,Kazakhstan,Silicon Metal,13000.0,5000.0,6000.0,7200.0,7000.0
0,Argentina,Ferrosilicon,13000.0,11200.0,13000.0,12500.0,12500.0

### 2. Germanium

In [4]:
germanium_df = pd.read_excel('data/raw/dataset1/myb1-2023-germanium.xlsx', sheet_name = 'T1', header = None)
germanium_df.to_csv('data/raw/dataset1/germanium_T1.csv', index = False)
print(f"dataset shape: {germanium_df.shape}")
germanium_df.info()

dataset shape: (36, 12)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       33 non-null     object
 1   1       3 non-null      object
 2   2       0 non-null      float64
 3   3       16 non-null     float64
 4   4       0 non-null      float64
 5   5       16 non-null     float64
 6   6       2 non-null      object
 7   7       12 non-null     float64
 8   8       0 non-null      float64
 9   9       11 non-null     float64
 10  10      1 non-null      object
 11  11      10 non-null     float64
dtypes: float64(8), object(4)
memory usage: 3.5+ KB

In [5]:
year_cols = [
    'production_2019_kg',
    'production_2020_kg',
    'production_2021_kg',
    'production_2022_kg',
    'production_2023_kg'
]

germanium_clean = germanium_df.iloc[24:27, [0, 3, 5, 7, 9, 11]].copy()
germanium_clean.columns = ['country'] + year_cols

germanium_clean['country'] = germanium_clean['country'].str.strip().str.replace(r'[0-9]+$', '', regex = True).str.strip()
germanium_clean[year_cols] = germanium_clean[year_cols].apply(pd.to_numeric, errors = 'coerce')
germanium_clean['material'] = 'Germanium'
germanium_clean = germanium_clean[['country', 'material'] + year_cols].reset_index(drop = True)

germanium_clean.to_csv('data/processed/dataset1/germanium_production_by_country.csv', index = False)
print(f"dataset shape: {germanium_clean.shape}")
germanium_clean

dataset shape: (3, 7)

,country,material,production_2019_kg,production_2020_kg,production_2021_kg,production_2022_kg,production_2023_kg
0,China,Germanium,85700.0,95000.0,NaN,NaN,NaN
1,Russia,Germanium,5000.0,5000.0,NaN,NaN,NaN
2,Other,Germanium,40000.0,40000.0,NaN,NaN,NaN

### 3. Gallium

In [6]:
gallium_df = pd.read_excel('data/raw/dataset1/myb1-2023-galli-ERT.xlsx', sheet_name = 'T7', header = None)
gallium_df.to_csv('data/raw/dataset1/gallium_T7.csv', index = False)
print(f"dataset shape: {gallium_df.shape}")
gallium_df.info()

dataset shape: (13, 12)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       11 non-null     object
 1   1       0 non-null      float64
 2   2       6 non-null      object
 3   3       1 non-null      object
 4   4       6 non-null      object
 5   5       1 non-null      object
 6   6       6 non-null      float64
 7   7       2 non-null      object
 8   8       6 non-null      object
 9   9       4 non-null      object
 10  10      6 non-null      object
 11  11      1 non-null      object
dtypes: float64(2), object(10)
memory usage: 1.3+ KB

In [7]:
year_cols = [
    'production_2019_kg',
    'production_2020_kg',
    'production_2021_kg',
    'production_2022_kg',
    'production_2023_kg'
]

gallium_clean = gallium_df.iloc[6:10, [0, 2, 4, 6, 8, 10]].copy()
gallium_clean.columns = ['country'] + year_cols

gallium_clean['country'] = gallium_clean['country'].str.strip().str.replace(r'e$', '', regex = True).str.strip()
gallium_clean['country'] = gallium_clean['country'].replace({'Russiae': 'Russia', 'Ukrain': 'Ukraine'})

gallium_clean[year_cols] = gallium_clean[year_cols].apply(pd.to_numeric, errors = 'coerce')
gallium_clean['material'] = 'Gallium'
gallium_clean = gallium_clean[['country', 'material'] + year_cols].reset_index(drop = True)

gallium_clean.to_csv('data/processed/dataset1/gallium_production_by_country.csv', index = False)
print(f"dataset shape: {gallium_clean.shape}")
gallium_clean

dataset shape: (4, 7)

,country,material,production_2019_kg,production_2020_kg,production_2021_kg,production_2022_kg,production_2023_kg
0,China,Gallium,338000.0,336400.0,423000.0,524000.0,621000.0
1,Japan,Gallium,3000.0,3000.0,3000.0,3000.0,3000.0
2,Russia,Gallium,8000.0,5000.0,8000.0,6000.0,6000.0
3,Ukraine,Gallium,NaN,NaN,1000.0,NaN,NaN

### 4. Arsenic

In [8]:
arsenic_df = pd.read_excel('data/raw/dataset1/myb1-2023-arsen-ert.xlsx', sheet_name = 'T3', header = None)
arsenic_df.to_csv('data/raw/dataset1/arsenic_T3.csv', index=False)
print(f"dataset shape: {arsenic_df.shape}")
arsenic_df.info()

dataset shape: (18, 12)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       16 non-null     object
 1   1       0 non-null      float64
 2   2       9 non-null      float64
 3   3       0 non-null      float64
 4   4       9 non-null      float64
 5   5       0 non-null      float64
 6   6       9 non-null      float64
 7   7       3 non-null      object
 8   8       9 non-null      float64
 9   9       5 non-null      object
 10  10      9 non-null      object
 11  11      3 non-null      object
dtypes: float64(7), object(5)
memory usage: 1.8+ KB

In [9]:
year_cols = [
    'production_2019_metric_tons',
    'production_2020_metric_tons',
    'production_2021_metric_tons',
    'production_2022_metric_tons',
    'production_2023_metric_tons'
]

arsenic_clean = arsenic_df.iloc[6:13, [0, 2, 4, 6, 8, 10]].copy()
arsenic_clean.columns = ['country'] + year_cols

arsenic_clean['country'] = arsenic_clean['country'].str.strip().str.rstrip('e').str.strip()
arsenic_clean[year_cols] = arsenic_clean[year_cols].apply(pd.to_numeric, errors = 'coerce')
arsenic_clean['material'] = 'Arsenic trioxide'
arsenic_clean = arsenic_clean[['country', 'material'] + year_cols].reset_index(drop = True)

arsenic_clean.to_csv('data/processed/dataset1/arsenic_production_by_country.csv', index = False)
print(f"dataset shape: {arsenic_clean.shape}")
arsenic_clean

dataset shape: (7, 7)

,country,material,production_2019_metric_tons,production_2020_metric_tons,production_2021_metric_tons,production_2022_metric_tons,production_2023_metric_tons
0,Belgium,Arsenic trioxide,1000.0,1000.0,1000.0,1000.0,1000.0
1,Bolivia,Arsenic trioxide,126.0,50.0,100.0,35.0,NaN
2,China,Arsenic trioxide,24000.0,24000.0,24000.0,24000.0,24000.0
3,Japan,Arsenic trioxide,45.0,40.0,40.0,40.0,40.0
4,Morocco,Arsenic trioxide,5055.0,7694.0,6883.0,5450.0,6000.0
5,Peru,Arsenic trioxide,35000.0,27000.0,30000.0,30000.0,30000.0
6,Russia,Arsenic trioxide,2226.0,500.0,800.0,500.0,500.0

## Dataset 2: USGS – U.S. Geological Survey Mineral Commodity Summaries 2025 Data Release

In [10]:
silicon_df = pd.read_csv('data/raw/dataset2/mcs2025-simet_salient.csv')
germanium_df = pd.read_csv('data/raw/dataset2/mcs2025-germa_salient.csv')
gallium_df = pd.read_csv('data/raw/dataset2/mcs2025-galli_salient.csv')
arsenic_df = pd.read_csv('data/raw/dataset2/mcs2025-arsen_salient.csv')

In [11]:
prices_clean = pd.DataFrame({
    'Year': silicon_df['Year'],
    'Silicon_cents_per_lb': silicon_df['Price_Si_ctslb'],
    'Germanium_USD_per_kg': germanium_df['Price_Metal_dkg'],
    'Gallium_USD_per_kg': gallium_df['Price_High-purity_dkg'],
    'Arsenic_USD_per_kg': arsenic_df['Price_Mtl_US_dkg']
})

prices_clean.to_csv('data/processed/dataset2/prices_clean.csv', index = False)
print(f"dataset shape: {prices_clean.shape}")
prices_clean

dataset shape: (5, 5)

,Year,Silicon_cents_per_lb,Germanium_USD_per_kg,Gallium_USD_per_kg,Arsenic_USD_per_kg
0,2020,96.84,1046,596,1.08
1,2021,220.31,1187,625,1.11
2,2022,361.86,1294,560,1.67
3,2023,179.69,1392,450,2.05
4,2024,180.00,2100,500,2.00

## Dataset 3: Global Trade Alert – Export Controls on Semiconductors

In [12]:
interventions_df = pd.read_csv('data/raw/dataset3/interventions.csv')
print(f"dataset shape: {interventions_df.shape}")
interventions_df.info()

dataset shape: (80, 19)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Intervention ID             80 non-null     int64
 1   Intervention URL            80 non-null     object
 2   State Act ID                80 non-null     int64
 3   State Act URL               80 non-null     object
 4   State Act Title             80 non-null     object
 5   GTA Evaluation              80 non-null     object
 6   Implementing Jurisdictions  80 non-null     object
 7   Implementation Level        80 non-null     object
 8   Eligible Firm               80 non-null     object
 9   Intervention Type           80 non-null     object
 10  Mast Chapter                80 non-null     object
 11  Affected Sectors            79 non-null     object
 12  Affected Products           79 non-null     object
 13  Affected Jurisdictions      79 non-null     object
 14  Is Horizontal               80 non-null     bool
 15  Date Announced              80 non-null     object
 16  Date Implemented            77 non-null     object
 17  Date Removed                3 non-null      object
 18  Is In Force                 80 non-null     int64
dtypes: bool(1), int64(3), object(15)
memory usage: 11.5+ KB

In [13]:
interventions_clean = interventions_df[
    interventions_df['Is In Force'] == 1
][['State Act Title', 'Implementing Jurisdictions', 'Implementation Level', 'Intervention Type', 'Affected Products', 'Affected Jurisdictions', 'Date Implemented', 'Is In Force']
    ].dropna(subset = ['Affected Products', 'Affected Jurisdictions']).copy()

interventions_clean['Date Implemented'] = pd.to_datetime(interventions_clean['Date Implemented'], errors = 'coerce')
interventions_clean['Year'] = interventions_clean['Date Implemented'].dt.year

interventions_clean.to_csv('data/processed/dataset3/interventions_clean.csv', index = False)
print(f"dataset shape: {interventions_clean.shape}")
interventions_clean.sample(5)

dataset shape: (74, 9)

,State Act Title,Implementing Jurisdictions,Implementation Level,Intervention Type,Affected Products,Affected Jurisdictions,Date Implemented,Is In Force,Year
60,United States of America: Government restricts...,United States of America,National,Export licensing requirement,"854151, 854159, 854231, 854232, 854233, 854239...",China,2024-11-10,1,2024
8,United States of America: Department of Commer...,United States of America,National,Export licensing requirement,"261210, 261220, 262099, 270710, 270720, 270730...",Russia,2022-02-24,1,2022
64,China: Government adopts further export contro...,China,National,Export ban,"121150, 121160, 121190, 130214, 130219, 220710...",United States of America,2024-12-03,1,2024
25,EU: 2023 update of the list of dual-use goods,"Austria, Belgium, Bulgaria, Croatia, Cyprus, C...",Supranational,Export licensing requirement,"293149, 293219, 293299, 293980, 760120, 850440...","Albania, Algeria, Angola, Azerbaijan, Argentin...",2023-01-12,1,2023
1,Australia: Government amends the Defence and S...,Australia,National,"Export-related non-tariff measure, nes","271019, 292121, 840810, 845931, 845951, 846222...","Austria, Brazil, Canada, China, Czechia, Fiji,...",2019-04-02,1,2019

## Dataset 4: Emerging Technology Observatory – Advanced Semiconductor Supply Chain Dataset

### 1. Inputs

In [14]:
inputs_df = pd.read_csv('data/raw/dataset4/inputs.csv')
print(f"dataset shape: {inputs_df.shape}")
inputs_df.info()

dataset shape: (126, 10)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 126 entries, 0 to 125
Data columns (total 10 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   input_id                                    126 non-null    object
 1   input_name                                  126 non-null    object
 2   type                                        126 non-null    object
 3   stage_name                                  11 non-null     object
 4   stage_id                                    11 non-null     object
 5   description                                 126 non-null    object
 6   year                                        104 non-null    float64
 7   market_share_chart_global_market_size_info  103 non-null    object
 8   market_share_chart_caption                  0 non-null      float64
 9   market_share_chart_source                   103 non-null    object
dtypes: float64(2), object(8)
memory usage: 10.0+ KB

In [15]:
inputs_clean = inputs_df[['input_name', 'type', 'stage_name', 'year', 'market_share_chart_global_market_size_info']
    ].dropna(subset = ['year']).copy()

inputs_clean['year'] = inputs_clean['year'].astype(int)

inputs_clean.to_csv('data/processed/dataset4/inputs_clean.csv', index = False)
print(f"dataset shape: {inputs_clean.shape}")
inputs_clean.sample(5)

dataset shape: (104, 5)

,input_name,type,stage_name,year,market_share_chart_global_market_size_info
31,Photomasks,material_resource,NaN,2019,$4 billion (all photomasks)
68,Defect review stations,tool_resource,NaN,2024,$618.1 million (2024)
4,FPGAs,design_resource,NaN,2019,$5.7 billion (2019)
64,Critical dimensions metrology tools,tool_resource,NaN,2024,$869.9 million (2024)
83,Packaging tools,tool_resource,NaN,2024,$675.9 million (2024)

### 2. Providers

In [16]:
providers_df = pd.read_csv('data/raw/dataset4/providers.csv')
print(f"dataset shape: {providers_df.shape}")
providers_df.info()

dataset shape: (397, 5)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397 entries, 0 to 396
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   provider_name  397 non-null    object
 1   alias          68 non-null     object
 2   provider_id    397 non-null    object
 3   provider_type  397 non-null    object
 4   country        375 non-null    object
dtypes: object(5)
memory usage: 15.6+ KB

In [17]:
providers_clean = providers_df[['provider_name', 'provider_type', 'country']].dropna(subset = ['country']).copy()

providers_clean.to_csv('data/processed/dataset4/providers_clean.csv', index = False)
print(f"dataset shape: {providers_clean.shape}")
providers_clean.sample(5)

dataset shape: (375, 3)

                   provider_name provider_type country
249                        Wonik  organization     KOR
246                         BASF  organization     DEU
151                        Hoson  organization     CHN
48   Tianshui Huatian Technology  organization     CHN
311          IMS Nanofabrication  organization     AUT

### 3. Provision

In [18]:
provision_df = pd.read_csv('data/raw/dataset4/provision.csv')
print(f"dataset shape: {provision_df.shape}")
provision_df.info()

dataset shape: (1305, 7)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1305 entries, 0 to 1304
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   provider_name   1305 non-null   object
 1   provider_id     1305 non-null   object
 2   provided_name   1297 non-null   object
 3   provided_id     1305 non-null   object
 4   share_provided  1051 non-null   float64
 5   year            1305 non-null   int64
 6   source          1170 non-null   object
dtypes: float64(1), int64(1), object(5)
memory usage: 71.5+ KB

In [19]:
provision_clean = provision_df[['provider_name', 'provided_name', 'share_provided', 'year']
    ].dropna(subset = ['provided_name', 'share_provided']).copy()

provision_clean.to_csv('data/processed/dataset4/provision_clean.csv', index = False)
print(f"dataset shape: {provision_clean.shape}")
provision_clean.sample(5)

dataset shape: (1051, 4)

,provider_name,provided_name,share_provided,year
936,Various countries,Resist processing tools,0.2,2024
223,DEU,Assembly inspection tools,2.2,2024
194,Chroma ATE,Test tools,1.7,2024
873,Various companies,Linear and discrete testing tools,3.7,2024
424,KLA,Inspection tools (adv. pkg.),39.7,2024

### 4. Sequence

In [20]:
sequence_df = pd.read_csv('data/raw/dataset4/sequence.csv')
print(f"dataset shape: {sequence_df.shape}")
sequence_df.info()

dataset shape: (139, 6)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 139 entries, 0 to 138
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   input_name       139 non-null    object
 1   input_id         139 non-null    object
 2   goes_into_name   53 non-null     object
 3   goes_into_id     53 non-null     object
 4   is_type_of_name  86 non-null     object
 5   is_type_of_id    86 non-null     object
dtypes: object(6)
memory usage: 6.6+ KB

In [21]:
sequence_clean = sequence_df[['input_name', 'goes_into_name', 'is_type_of_name']].copy()

sequence_clean.to_csv('data/processed/dataset4/sequence_clean.csv', index = False)
print(f"dataset shape: {sequence_clean.shape}")
sequence_clean.sample(5)

dataset shape: (139, 3)

,input_name,goes_into_name,is_type_of_name
99,Spin-on deposition tools (adv. pkg.),NaN,Deposition tools (adv. pkg.)
4,ArF immersion (DUV) lithography tools,NaN,Lithography tools
40,Wafer inspection tools,NaN,Process control tools
0,Crystal growing furnaces,Wafer,NaN
122,CMP materials,NaN,Process-specific fabrication materials

## Dataset 5: FRED – Producer Price Index by Industry: Semiconductor and Other Electronic Component Manufacturing

In [22]:
chip_price_df = pd.read_csv('data/raw/dataset5/PCU33443344.csv')
print(f"dataset shape: {chip_price_df.shape}")
chip_price_df.info()

dataset shape: (493, 2)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 493 entries, 0 to 492
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   observation_date  493 non-null    object
 1   PCU33443344       493 non-null    float64
dtypes: float64(1), object(1)
memory usage: 7.8+ KB

In [23]:
chip_price_clean = chip_price_df.copy()
chip_price_clean['observation_date'] = pd.to_datetime(chip_price_clean['observation_date'])
chip_price_clean['Year'] = chip_price_clean['observation_date'].dt.year
chip_price_clean['Month'] = chip_price_clean['observation_date'].dt.month
chip_price_clean.rename(columns = {
    'PCU33443344': 'Price_Index'
}, inplace = True)

chip_price_clean = chip_price_clean[chip_price_clean['Year'] >= 2015].copy()

chip_price_clean.to_csv('data/processed/dataset5/chip_price_clean.csv', index = False)
print(f"dataset shape: {chip_price_clean.shape}")
chip_price_clean.sample(5)

dataset shape: (132, 4)

    observation_date  Price_Index  Year  Month
439       2021-07-01       54.548  2021      7
488       2025-08-01       59.626  2025      8
414       2019-06-01       55.300  2019      6
361       2015-01-01       58.700  2015      1
417       2019-09-01       55.600  2019      9

## Dataset 6: OECD – Analytical Business Enterprise R&D by ISIC Rev.4 industry

In [24]:
oecd_df = pd.read_csv('data/raw/dataset6/OECD.csv')
print(f"dataset shape: {oecd_df.shape}")
oecd_df.info()

dataset shape: (62, 30)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 30 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   STRUCTURE                 62 non-null     object
 1   STRUCTURE_ID              62 non-null     object
 2   STRUCTURE_NAME            62 non-null     object
 3   ACTION                    62 non-null     object
 4   REF_AREA                  62 non-null     object
 5   Reference area            62 non-null     object
 6   FREQ                      62 non-null     object
 7   Frequency of observation  62 non-null     object
 8   CRITERIA                  62 non-null     object
 9   Classification criteria   62 non-null     object
 10  ACTIVITY                  62 non-null     object
 11  Economic activity         62 non-null     object
 12  UNIT_MEASURE              62 non-null     object
 13  Unit of measure           62 non-null     object
 14  PRICE_BASE                62 non-null     object
 15  Price base                62 non-null     object
 16  MEASURE                   62 non-null     object
 17  Measure                   62 non-null     object
 18  TIME_PERIOD               62 non-null     int64
 19  Time period               0 non-null      float64
 20  OBS_VALUE                 62 non-null     int64
 21  Observation value         0 non-null      float64
 22  OBS_STATUS                7 non-null      object
 23  Observation status        7 non-null      object
 24  UNIT_MULT                 62 non-null     int64
 25  Unit multiplier           62 non-null     object
 26  DECIMALS                  62 non-null     int64
 27  Decimals                  62 non-null     object
 28  BASE_PER                  0 non-null      float64
 29  Base year                 0 non-null      float64
dtypes: float64(4), int64(4), object(22)
memory usage: 14.7+ KB

In [25]:
oecd_clean = oecd_df[['Reference area', 'Economic activity', 'TIME_PERIOD', 'OBS_VALUE', 'Unit of measure']].copy()
oecd_clean.rename(columns = {
    'Reference area': 'Country',
    'TIME_PERIOD': 'Year',
    'OBS_VALUE': 'Investment amount'
}, inplace = True)

oecd_clean.to_csv('data/processed/dataset6/oecd_investment_clean.csv', index = False)
print(f"dataset shape: {oecd_clean.shape}")
oecd_clean.sample(5)

dataset shape: (62, 5)

,Country,Economic activity,Year,Investment amount,Unit of measure
44,Korea,Manufacture of electronic components and boards,2018,9011165000000,National currency
4,France,"Manufacture of computer, electronic and optica...",2021,3904634000,National currency
49,Japan,Manufacture of electronic components and boards,2022,1231097000000,National currency
6,Chinese Taipei,"Manufacture of computer, electronic and optica...",2021,540389030365,National currency
1,Korea,"Manufacture of computer, electronic and optica...",2021,39873978000000,National currency

## Dataset 7: European Commission – The 2025 EU Industrial R&D Investment Scoreboard

In [26]:
eu_scoreboard_df = pd.read_excel('data/raw/dataset7/SB2025_World2000_2.xlsx')
eu_scoreboard_df.to_csv('data/raw/dataset7/SB2025_World2000_2.csv', index = False)
print(f"dataset shape: {eu_scoreboard_df.shape}")
eu_scoreboard_df.info()

dataset shape: (2000, 24)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 24 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Year                                       2000 non-null   int64
 1   World rank                                 2000 non-null   int64
 2   Company                                    2000 non-null   object
 3   Country                                    2000 non-null   object
 4   Region                                     2000 non-null   object
 5   ISO3 Code                                  2000 non-null   object
 6   ICB3 short                                 2000 non-null   object
 7   ICB3 long                                  2000 non-null   object
 8   R&D (€million)                             2000 non-null   float64
 9   R&D one-year growth (%)                    1975 non-null   float64
 10  Net sales (€million)                       2000 non-null   float64
 11  Net sales one-year growth (%)              1927 non-null   float64
 12  R&D intensity (%)                          1957 non-null   float64
 13  Capex (€million)                           1998 non-null   float64
 14  Capex one-year growth (%)                  1967 non-null   float64
 15  Capex intensity (%)                        1955 non-null   float64
 16  R&D-to-capex ratio (%)                     1985 non-null   float64
 17  Operating profit (€million)                2000 non-null   float64
 18  Operating profit one-year growth (%)       1975 non-null   float64
 19  Profitability (%)                          1957 non-null   float64
 20  Market capitalisation (€million)           1874 non-null   float64
 21  Market capitalisation one-year growth (%)  1848 non-null   float64
 22  Employees                                  1892 non-null   float64
 23  Employees one-year growth (%)              1868 non-null   float64
dtypes: float64(16), int64(2), object(6)
memory usage: 375.1+ KB

In [27]:
semiconductor_sectors = [
    'Technology Hardware & Equipment',
    'Electronic & Electrical Equipment',
    'Software & Computer Services'
]

eu_scoreboard_clean = eu_scoreboard_df[
    eu_scoreboard_df['ICB3 long'].isin(semiconductor_sectors)
][[
    'Year',
    'Company',
    'Country',
    'ICB3 long',
    'R&D (€million)',
    'R&D one-year growth (%)',
    'R&D intensity (%)',
    'Capex (€million)',
    'Capex one-year growth (%)',
    'Capex intensity (%)',
    'R&D-to-capex ratio (%)',
    'Net sales (€million)',
    'Net sales one-year growth (%)',
    'Operating profit (€million)',
    'Operating profit one-year growth (%)',
    'Profitability (%)',
    'Market capitalisation (€million)',
    'Market capitalisation one-year growth (%)',
    'Employees',
    'Employees one-year growth (%)'
]].dropna(subset = ['R&D (€million)', 'Market capitalisation (€million)']).copy()

eu_scoreboard_clean.to_csv('data/processed/dataset7/eu_scoreboard_clean.csv', index = False)
print(f"dataset shape: {eu_scoreboard_clean.shape}")
eu_scoreboard_clean.sample(5)

dataset shape: (640, 20)

,Year,Company,Country,ICB3 long,R&D (€million),R&D one-year growth (%),R&D intensity (%),Capex (€million),Capex one-year growth (%),Capex intensity (%),R&D-to-capex ratio (%),Net sales (€million),Net sales one-year growth (%),Operating profit (€million),Operating profit one-year growth (%),Profitability (%),Market capitalisation (€million),Market capitalisation one-year growth (%),Employees,Employees one-year growth (%)
1543,2024,"SHENZHEN DESAY BATTERY TECHNOLOGY CO., LTD.",China,Electronic & Electrical Equipment,104.775686,37.580091,3.809079,155.437460,-35.430906,5.650869,67.406973,2750.682630,2.831328,41.700920,-44.389214,1.516021,1192.174169,-13.300760,16272.0,48.752171
1731,2024,NEXANS,France,Electronic & Electrical Equipment,89.000000,0.000000,1.041423,378.000000,0.265252,4.423122,23.544974,8546.000000,9.704750,601.000000,56.510417,7.032530,4559.102062,31.482646,28498.0,-0.007018
1852,2024,AZBIL CORPORATION,Japan,Electronic & Electrical Equipment,78.051024,3.261663,4.236981,40.230590,3.339635,2.183908,194.009146,1842.137863,3.245021,254.427818,12.610950,13.811551,3993.593791,9.723927,8922.0,-9.960642
109,2024,SCHNEIDER ELECTRIC SE,France,Electronic & Electrical Equipment,2260.000000,12.103175,5.923518,950.000000,3.938731,2.489975,237.894737,38153.000000,6.269846,6590.000000,15.919085,17.272560,138669.667235,33.169620,167495.0,9.387347
513,2024,"WINGTECH TECHNOLOGY CO.,LTD",China,Technology Hardware & Equipment,415.890402,-7.379727,4.285201,402.488184,-37.595882,4.147109,103.329841,9705.271573,20.232997,-248.720388,-174.737017,-2.562735,6364.593073,-8.212942,29482.0,-6.397435

## Dataset 8: Kaggle – Top Semiconductor Companies by Market Capital

In [28]:
sc_data_df = pd.read_csv('data/raw/dataset8/sc_data.csv')
print(f"dataset shape: {sc_data_df.shape}")
sc_data_df.info()

dataset shape: (152, 6)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 152 entries, 0 to 151
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   rank                   152 non-null    int64
 1   name                   152 non-null    object
 2   ticker                 152 non-null    object
 3   market_cap_04_08_2025  152 non-null    int64
 4   price_04_08_2025       152 non-null    float64
 5   country                152 non-null    object
dtypes: float64(1), int64(2), object(3)
memory usage: 7.3+ KB

In [29]:
sc_data_clean = sc_data_df[['rank', 'name', 'ticker', 'country', 'market_cap_04_08_2025', 'price_04_08_2025']].copy()

sc_data_clean.rename(columns = {
    'name': 'company',
    'market_cap_04_08_2025': 'market_cap_usd',
    'price_04_08_2025': 'stock_price_usd'
}, inplace = True)
sc_data_clean['Data_Date'] = '2025-04-08'

sc_data_clean.to_csv('data/processed/dataset8/semiconductor_companies_clean.csv', index = False)
print(f"dataset shape: {sc_data_clean.shape}")
sc_data_clean.sample(5)

dataset shape: (152, 7)

,rank,company,ticker,country,market_cap_usd,stock_price_usd,Data_Date
25,26,Monolithic Power Systems,MPWR,United States,37615484928,785.62000,2025-04-08
127,128,CEVA,CEVA,United States,495069504,20.70000,2025-04-08
79,80,Camtek,CAMT,Israel,4355105792,95.50000,2025-04-08
50,51,San’an Optoelectronics,600703.SS,China,8772086640,1.75828,2025-04-08
84,85,Espressif Systems (Shanghai),688018.SS,China,3486900699,22.25170,2025-04-08