In [25]:
import pandas as pd
import altair as alt
import numpy as np

# **Topic**: AI Semiconductors

## **Dataset 1**: Kaggle – Open Database on Global Coal and Metal Mining

### **1. material_ids.csv**

In [119]:
material_ids_df = pd.read_csv('data/raw/dataset1/material_ids.csv')

# search for Silicon (Si)
silicon = material_ids_df[material_ids_df['material_name'].str.contains("Silicon")]
print("Silicon (Si):")
print(silicon[['material_id', 'material_name']])

# search for Germanium (Ge)
germanium = material_ids_df[material_ids_df['material_name'].str.contains("Germanium")]
print("\nGermanium (Ge):")
print(germanium[['material_id', 'material_name']])

# search for Gallium Arsenide (GaAs)
# search for Gallium (Ga)
gallium = material_ids_df[material_ids_df['material_name'].str.contains("Gallium")]
print("\nGallium (Ga):")
print(gallium[['material_id', 'material_name']])

# search for Arsenide (As)
# since Arsenide is a byproduct of copper mining, and it is absent in this dataset, I use "Copper dominant ore" to represent
arsenide = material_ids_df[material_ids_df['material_name'].str.contains("Copper dominant ore")]
print("\nArsenide (As):")
print(arsenide[['material_id', 'material_name']])

Silicon (Si):
    material_id material_name
199       Me.Si       Silicon

Germanium (Ge):
    material_id material_name
131       Me.Ge     Germanium

Gallium (Ga):
    material_id material_name
130       Me.Ga       Gallium

Arsenide (As):
  material_id        material_name
7        O.Cu  Copper dominant ore

### **2. commodities.csv**

In [110]:
commodities_df = pd.read_csv('data/raw/dataset1/commodities.csv')
print(f"dataset shape: {commodities_df.shape}")
commodities_df.info()

dataset shape: (9426, 16)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9426 entries, 0 to 9425
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    9426 non-null   int64
 1   facility_id           9426 non-null   object
 2   year                  9426 non-null   int64
 3   material              8895 non-null   object
 4   commodity             9426 non-null   object
 5   value_tonnes          9399 non-null   float64
 6   grade_ppm             7132 non-null   float64
 7   recovery_rate         5497 non-null   float64
 8   yield_ppm             127 non-null    float64
 9   amount_sold_tonnes    1423 non-null   float64
 10  metal_payable_tonnes  429 non-null    float64
 11  mine_processing       473 non-null    object
 12  reporting_period      1233 non-null   object
 13  source_id             9426 non-null   object
 14  comment               386 non-null    object
 15  id_minerals           7053 non-null   float64
dtypes: float64(7), int64(2), object(7)
memory usage: 1.2+ MB

In [162]:
raw_materials = {
    'Me.Si': 'Silicon',
    'Me.Ge': 'Germanium', 
    'Me.Ga': 'Gallium',
    'O.Cu': 'Copper_dominant_ore'  # represents arsenic-bearing copper ore
}

commodities_clean_df = commodities_df[
    (commodities_df['commodity'].isin(raw_materials.keys())) & (commodities_df['value_tonnes'].notna())
].copy()

print(f"Original data: {len(commodities_df)} rows")
print(f"Filtered data: {len(commodities_clean_df)} rows")

Original data: 9426 rows
Filtered data: 0 rows

### **3. ownership.csv**

In [160]:
ownership_df = pd.read_csv('data/raw/dataset1/ownership.csv')
print(f"dataset shape: {ownership_df.shape}")
ownership_df.info()

dataset shape: (699, 7)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699 entries, 0 to 698
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           699 non-null    int64
 1   facility_id  699 non-null    object
 2   year         699 non-null    int64
 3   owners       698 non-null    object
 4   operators    143 non-null    object
 5   source_id    699 non-null    object
 6   comment      8 non-null      object
dtypes: int64(2), object(5)
memory usage: 38.4+ KB

In [185]:
interest_cols = ['facility_id', 'year', 'owners']
valid_rows = (ownership_df['owners'].notna()) & (ownership_df['year'] >= 2015)
ownership_clean = ownership_df[valid_rows][interest_cols].copy()

print(f"dataset shape: {ownership_clean.shape}")
ownership_clean_df.sample(5)

dataset shape: (630, 3)

     facility_id  year                                             owners
328  COM00666.00  2017                       Cleveland-Cliffs Inc. (100%)
530  COM01085.00  2018                                   Rio Tinto (100%)
306  COM00622.00  2020                               PAO Severstal (100%)
45   COM00099.00  2015                                   Rio Tinto (100%)
425  COM00859.00  2019  South32 (47.1%),  Industrial Development Corpo...

### **Dataset 2**: USGS – U.S. Geological Survey Mineral Commodity Summaries 2025 Data Release

In [186]:
silicon_df = pd.read_csv('data/raw/dataset2/mcs2025-simet_salient.csv')
germanium_df = pd.read_csv('data/raw/dataset2/mcs2025-germa_salient.csv')
gallium_df = pd.read_csv('data/raw/dataset2/mcs2025-galli_salient.csv')
arsenic_df = pd.read_csv('data/raw/dataset2/mcs2025-arsen_salient.csv')

In [187]:
prices_clean = pd.DataFrame({
    'Year': silicon_df['Year'],
    'Silicon_cents_per_lb': silicon_df['Price_Si_ctslb'],
    'Germanium_USD_per_kg': germanium_df['Price_Metal_dkg'],
    'Gallium_USD_per_kg': gallium_df['Price_High-purity_dkg'],
    'Arsenic_USD_per_kg': arsenic_df['Price_Mtl_US_dkg']
})

prices_clean.to_csv('data/processed/dataset2/prices_clean.csv', index = False)
print(f"dataset shape: {prices_clean.shape}")
prices_clean

dataset shape: (5, 5)

,Year,Silicon_cents_per_lb,Germanium_USD_per_kg,Gallium_USD_per_kg,Arsenic_USD_per_kg
0,2020,96.84,1046,596,1.08
1,2021,220.31,1187,625,1.11
2,2022,361.86,1294,560,1.67
3,2023,179.69,1392,450,2.05
4,2024,180.00,2100,500,2.00

### **Dataset 3**: Global Trade Alert – Export Controls on Semiconductors

In [108]:
interventions_df = pd.read_csv('data/raw/dataset3/interventions.csv')
print(f"dataset shape: {interventions_df.shape}")
interventions_df.info()

dataset shape: (80, 19)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Intervention ID             80 non-null     int64
 1   Intervention URL            80 non-null     object
 2   State Act ID                80 non-null     int64
 3   State Act URL               80 non-null     object
 4   State Act Title             80 non-null     object
 5   GTA Evaluation              80 non-null     object
 6   Implementing Jurisdictions  80 non-null     object
 7   Implementation Level        80 non-null     object
 8   Eligible Firm               80 non-null     object
 9   Intervention Type           80 non-null     object
 10  Mast Chapter                80 non-null     object
 11  Affected Sectors            79 non-null     object
 12  Affected Products           79 non-null     object
 13  Affected Jurisdictions      79 non-null     object
 14  Is Horizontal               80 non-null     bool
 15  Date Announced              80 non-null     object
 16  Date Implemented            77 non-null     object
 17  Date Removed                3 non-null      object
 18  Is In Force                 80 non-null     int64
dtypes: bool(1), int64(3), object(15)
memory usage: 11.5+ KB

In [188]:
interventions_clean = interventions_df[
    interventions_df['Is In Force'] == 1
][['State Act Title', 'Implementing Jurisdictions', 'Implementation Level', 'Intervention Type', 'Affected Products', 'Affected Jurisdictions', 'Date Implemented', 'Is In Force']
    ].dropna(subset=['Affected Products', 'Affected Jurisdictions']).copy()

interventions_clean['Date Implemented'] = pd.to_datetime(interventions_clean['Date Implemented'], errors = 'coerce')
interventions_clean['Year'] = interventions_clean['Date Implemented'].dt.year

interventions_clean.to_csv('data/processed/dataset3/restrictions_clean.csv', index = False)
print(f"dataset shape: {interventions_clean.shape}")
interventions_clean.sample(5)

dataset shape: (74, 9)

,State Act Title,Implementing Jurisdictions,Implementation Level,Intervention Type,Affected Products,Affected Jurisdictions,Date Implemented,Is In Force,Year
2,United States of America: Further restrictions...,United States of America,National,Export licensing requirement,"854149, 854151, 854159, 854190",China,2020-08-17,1,2020
26,EU: New sanctions package targetting Russia in...,"Austria, Belgium, Bulgaria, Croatia, Cyprus, C...",Supranational,Export ban,"240412, 240492, 261210, 261220, 262099, 270710...","Iran, Russia",2023-02-26,1,2023
57,EU: Expanded export ban to Iran given its invo...,"Austria, Belgium, Bulgaria, Croatia, Cyprus, C...",Supranational,Export ban,"850110, 850120, 850131, 850132, 850133, 850134...",Iran,2024-05-16,1,2024
60,United States of America: Government restricts...,United States of America,National,Export licensing requirement,"854151, 854159, 854231, 854232, 854233, 854239...",China,2024-11-10,1,2024
36,EU: 11th sanctions package against Russia incl...,"Austria, Belgium, Bulgaria, Croatia, Cyprus, C...",Supranational,Export ban,"240412, 240492, 261210, 261220, 262099, 270710...",Syria,2023-06-24,1,2023

### **Dataset 4**: Emerging Technology Observatory – Advanced Semiconductor Supply Chain Dataset

### **1. inputs.csv**

In [113]:
inputs_df = pd.read_csv('data/raw/dataset4/inputs.csv')
print(f"dataset shape: {inputs_df.shape}")
inputs_df.info()

dataset shape: (126, 10)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 126 entries, 0 to 125
Data columns (total 10 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   input_id                                    126 non-null    object
 1   input_name                                  126 non-null    object
 2   type                                        126 non-null    object
 3   stage_name                                  11 non-null     object
 4   stage_id                                    11 non-null     object
 5   description                                 126 non-null    object
 6   year                                        104 non-null    float64
 7   market_share_chart_global_market_size_info  103 non-null    object
 8   market_share_chart_caption                  0 non-null      float64
 9   market_share_chart_source                   103 non-null    object
dtypes: float64(2), object(8)
memory usage: 10.0+ KB

In [189]:
inputs_clean = inputs_df[['input_name', 'type', 'stage_name', 'year', 'market_share_chart_global_market_size_info']
    ].dropna(subset = ['year']).copy()

inputs_clean.to_csv('data/processed/dataset4/inputs_clean.csv', index = False)
print(f"dataset shape: {inputs_clean.shape}")
inputs_clean.sample(5)

dataset shape: (104, 5)

,input_name,type,stage_name,year,market_share_chart_global_market_size_info
53,Ion milling tools,tool_resource,NaN,2024.0,$0.4 million (2024)
68,Defect review stations,tool_resource,NaN,2024.0,$618.1 million (2024)
40,Rapid thermal processing tools,tool_resource,NaN,2024.0,$1.4 billion (2024)
64,Critical dimensions metrology tools,tool_resource,NaN,2024.0,$869.9 million (2024)
76,Wire bonding tools,tool_resource,NaN,2024.0,$702.5 million (2024)

### **2. providers.csv**

In [124]:
providers_df = pd.read_csv('data/raw/dataset4/providers.csv')
print(f"dataset shape: {providers_df.shape}")
providers_df.info()

dataset shape: (397, 5)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397 entries, 0 to 396
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   provider_name  397 non-null    object
 1   alias          68 non-null     object
 2   provider_id    397 non-null    object
 3   provider_type  397 non-null    object
 4   country        375 non-null    object
dtypes: object(5)
memory usage: 15.6+ KB

In [191]:
providers_clean = providers_df[['provider_name', 'provider_type', 'country']].dropna(subset = ['country']).copy()

providers_clean.to_csv('data/processed/dataset4/providers_clean.csv', index = False)
print(f"dataset shape: {providers_clean.shape}")
providers_clean.sample(5)

dataset shape: (375, 3)

                    provider_name provider_type country
271                            LG  organization     KOR
301  ELES Semiconductor Equipment  organization     ITA
375   Gallant Precision Machining  organization     TWN
352              Trion Technology  organization     USA
137                 Keysight Tech  organization     USA

### **3. provision.csv**

In [192]:
provision_df = pd.read_csv('data/raw/dataset4/provision.csv')
print(f"dataset shape: {provision_df.shape}")
provision_df.info()

dataset shape: (1305, 7)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1305 entries, 0 to 1304
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   provider_name   1305 non-null   object
 1   provider_id     1305 non-null   object
 2   provided_name   1297 non-null   object
 3   provided_id     1305 non-null   object
 4   share_provided  1051 non-null   float64
 5   year            1305 non-null   int64
 6   source          1170 non-null   object
dtypes: float64(1), int64(1), object(5)
memory usage: 71.5+ KB

In [193]:
provision_clean = provision_df[['provider_name', 'provided_name', 'share_provided', 'year']
    ].dropna(subset = ['provided_name', 'share_provided']).copy()

provision_clean.to_csv('data/processed/dataset4/provision_clean.csv', index = False)
print(f"dataset shape: {provision_clean.shape}")
provision_clean.sample(5)

dataset shape: (1051, 4)

,provider_name,provided_name,share_provided,year
632,SAMCO,Misc. dry etch tools,8.3,2024
1026,USA,DAO chip design,41.0,2022
390,JPN,Bonding tools,13.7,2024
403,Jingsheng Electromechanical,Other deposition tools (non-IC),3.2,2024
674,SWE,Lithography tools,0.2,2024

### **4. sequence.csv**

In [194]:
sequence_df = pd.read_csv('data/raw/dataset4/sequence.csv')
print(f"dataset shape: {sequence_df.shape}")
sequence_df.info()

dataset shape: (139, 6)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 139 entries, 0 to 138
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   input_name       139 non-null    object
 1   input_id         139 non-null    object
 2   goes_into_name   53 non-null     object
 3   goes_into_id     53 non-null     object
 4   is_type_of_name  86 non-null     object
 5   is_type_of_id    86 non-null     object
dtypes: object(6)
memory usage: 6.6+ KB

In [202]:
sequence_clean = sequence_df[['input_name', 'goes_into_name', 'is_type_of_name']].copy()

sequence_clean.to_csv('data/processed/dataset4/sequence_clean.csv', index = False)
print(f"dataset shape: {sequence_clean.shape}")
sequence_clean.sample(5)

dataset shape: (139, 3)

,input_name,goes_into_name,is_type_of_name
59,Linear and discrete testing tools,NaN,Test tools
84,Direct write systems,NaN,Maskless lithography tools
76,Testing,Finished logic chip,NaN
71,Bond wires,NaN,Packaging materials
107,Process control tools,Process control and handling,NaN

### **Dataset 5**: FRED – Producer Price Index by Industry: Semiconductor and Other Electronic Component Manufacturing

In [197]:
chip_price_df = pd.read_csv('data/raw/dataset5/PCU33443344.csv')
print(f"dataset shape: {chip_price_df.shape}")
chip_price_df.info()

dataset shape: (493, 2)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 493 entries, 0 to 492
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   observation_date  493 non-null    object
 1   PCU33443344       493 non-null    float64
dtypes: float64(1), object(1)
memory usage: 7.8+ KB

In [198]:
chip_price_clean = chip_price_df.copy()
chip_price_clean['observation_date'] = pd.to_datetime(chip_price_clean['observation_date'])
chip_price_clean['Year'] = chip_price_clean['observation_date'].dt.year
chip_price_clean['Month'] = chip_price_clean['observation_date'].dt.month
chip_price_clean.rename(columns = {
    'PCU33443344': 'Price_Index'
}, inplace = True)

chip_price_clean = chip_price_clean[chip_price_clean['Year'] >= 2015].copy()

chip_price_clean.to_csv('data/processed/dataset5/chip_price_clean.csv', index = False)
print(f"dataset shape: {chip_price_clean.shape}")
chip_price_clean.sample(5)

dataset shape: (132, 4)

    observation_date  Price_Index  Year  Month
433       2021-01-01       54.100  2021      1
400       2018-04-01       56.400  2018      4
455       2022-11-01       57.591  2022     11
379       2016-07-01       57.400  2016      7
412       2019-04-01       55.200  2019      4

### **Dataset 6**: OECD – Analytical Business Enterprise R&D by ISIC Rev.4 industry

In [152]:
oecd_df = pd.read_csv('data/raw/dataset6/OECD.csv')
print(f"dataset shape: {oecd_df.shape}")
oecd_df.info()

dataset shape: (62, 30)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 30 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   STRUCTURE                 62 non-null     object
 1   STRUCTURE_ID              62 non-null     object
 2   STRUCTURE_NAME            62 non-null     object
 3   ACTION                    62 non-null     object
 4   REF_AREA                  62 non-null     object
 5   Reference area            62 non-null     object
 6   FREQ                      62 non-null     object
 7   Frequency of observation  62 non-null     object
 8   CRITERIA                  62 non-null     object
 9   Classification criteria   62 non-null     object
 10  ACTIVITY                  62 non-null     object
 11  Economic activity         62 non-null     object
 12  UNIT_MEASURE              62 non-null     object
 13  Unit of measure           62 non-null     object
 14  PRICE_BASE                62 non-null     object
 15  Price base                62 non-null     object
 16  MEASURE                   62 non-null     object
 17  Measure                   62 non-null     object
 18  TIME_PERIOD               62 non-null     int64
 19  Time period               0 non-null      float64
 20  OBS_VALUE                 62 non-null     int64
 21  Observation value         0 non-null      float64
 22  OBS_STATUS                7 non-null      object
 23  Observation status        7 non-null      object
 24  UNIT_MULT                 62 non-null     int64
 25  Unit multiplier           62 non-null     object
 26  DECIMALS                  62 non-null     int64
 27  Decimals                  62 non-null     object
 28  BASE_PER                  0 non-null      float64
 29  Base year                 0 non-null      float64
dtypes: float64(4), int64(4), object(22)
memory usage: 14.7+ KB

In [199]:
oecd_clean = oecd_df[['Reference area', 'Economic activity', 'TIME_PERIOD', 'OBS_VALUE', 'Unit of measure']].copy()
oecd_clean.rename(columns = {
    'Reference area': 'Country',
    'TIME_PERIOD': 'Year',
    'OBS_VALUE': 'Investment amount'
}, inplace = True)

oecd_clean.to_csv('data/processed/dataset6/oecd_investment_clean.csv', index = False)
print(f"dataset shape: {oecd_clean.shape}")
oecd_clean.sample(5)

dataset shape: (62, 5)

,Country,Economic activity,Year,Investment amount,Unit of measure
31,United States,Manufacture of electronic components and boards,2020,43952000000,National currency
58,France,"Manufacture of computer, electronic and optica...",2020,3954629692,National currency
60,France,Manufacture of electronic components and boards,2019,1165522934,National currency
13,Korea,Manufacture of electronic components and boards,2019,9224359000000,National currency
45,United Kingdom,"Manufacture of computer, electronic and optica...",2022,1800930000,National currency

### **Dataset 7**: European Commission – The 2025 EU Industrial R&D Investment Scoreboard

In [200]:
eu_scoreboard_df = pd.read_excel('data/raw/dataset7/SB2025_EU800.xlsx')
eu_scoreboard_df.to_csv('data/raw/dataset7/SB2025_EU800.csv', index = False)
print(f"dataset shape: {eu_scoreboard_df.shape}")
eu_scoreboard_df.info()

dataset shape: (800, 24)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 24 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Year                                       800 non-null    int64
 1   World rank                                 318 non-null    float64
 2   EU rank                                    800 non-null    int64
 3   Company                                    800 non-null    object
 4   Country                                    800 non-null    object
 5   ISO3 Code                                  800 non-null    object
 6   ICB3 short                                 800 non-null    object
 7   ICB3 long                                  800 non-null    object
 8   R&D (€million)                             800 non-null    float64
 9   R&D one-year growth (%)                    768 non-null    float64
 10  Net sales (€million)                       799 non-null    float64
 11  Net sales one-year growth (%)              752 non-null    float64
 12  R&D intensity (%)                          782 non-null    float64
 13  Capex (€million)                           800 non-null    float64
 14  Capex one-year growth (%)                  755 non-null    float64
 15  Capex intensity (%)                        782 non-null    float64
 16  R&D-to-capex ratio (%)                     785 non-null    float64
 17  Operating profit (€million)                799 non-null    float64
 18  Operating profit one-year growth (%)       766 non-null    float64
 19  Profitability (%)                          781 non-null    float64
 20  Market capitalisation (€million)           567 non-null    float64
 21  Market capitalisation one-year growth (%)  544 non-null    float64
 22  Employees                                  798 non-null    float64
 23  Employees one-year growth (%)              765 non-null    float64
dtypes: float64(17), int64(2), object(5)
memory usage: 150.1+ KB

In [201]:
semiconductor_sectors = [
    'Technology Hardware & Equipment',
    'Electronic & Electrical Equipment',
    'Software & Computer Services'
]

eu_scoreboard_clean = eu_scoreboard_df[
    eu_scoreboard_df['ICB3 long'].isin(semiconductor_sectors)
][[
    'Year',
    'Company',
    'Country',
    'ICB3 long',
    'R&D (€million)',
    'R&D one-year growth (%)',
    'R&D intensity (%)',
    'Capex (€million)',
    'Capex one-year growth (%)',
    'Capex intensity (%)',
    'R&D-to-capex ratio (%)',
    'Net sales (€million)',
    'Net sales one-year growth (%)',
    'Operating profit (€million)',
    'Operating profit one-year growth (%)',
    'Profitability (%)',
    'Market capitalisation (€million)',
    'Market capitalisation one-year growth (%)',
    'Employees',
    'Employees one-year growth (%)'
]].dropna(subset = ['Market capitalisation (€million)']).copy()

eu_scoreboard_clean.to_csv('data/processed/dataset7/eu_scoreboard_clean.csv', index = False)
print(f"dataset shape: {eu_scoreboard_clean.shape}")
eu_scoreboard_clean.sample(5)

dataset shape: (129, 20)

,Year,Company,Country,ICB3 long,R&D (€million),R&D one-year growth (%),R&D intensity (%),Capex (€million),Capex one-year growth (%),Capex intensity (%),R&D-to-capex ratio (%),Net sales (€million),Net sales one-year growth (%),Operating profit (€million),Operating profit one-year growth (%),Profitability (%),Market capitalisation (€million),Market capitalisation one-year growth (%),Employees,Employees one-year growth (%)
509,2024,INIT INNOVATION IN TRAFFIC SYSTEMS SE,Germany,Electronic & Electrical Equipment,25.172000,26.086957,9.474770,6.628000,62.133072,2.494787,379.782740,265.674000,26.030711,23.198000,18.429651,8.731754,357.423985,21.088432,1361.0,19.385965
107,2024,WISETECH GLOBAL LIMITED,Austria,Software & Computer Services,335.857381,42.211563,54.075070,14.905795,-8.088235,2.399923,2253.200000,621.094682,27.534280,226.985452,26.773227,36.546031,18691.364042,31.098701,3494.0,15.465962
141,2024,GN STORE NORD A/S,Denmark,Technology Hardware & Equipment,244.576148,5.923345,10.141785,16.090536,29.032258,0.667223,1520.000000,2411.569095,-0.745033,239.748988,122.388060,9.941618,2720.016369,-21.759206,7347.0,2.540126
742,2024,LS TELCOM AG,Germany,Technology Hardware & Equipment,7.570000,-18.549602,20.516573,6.064000,-3.177391,16.434941,124.835092,36.897000,-11.534957,-1.960000,-204.421950,-5.312085,18.381720,-15.508019,288.0,0.699301
220,2024,FOCUS ENTERTAINMENT SA,France,Software & Computer Services,121.926000,8.595858,31.263077,94.449000,14.761847,24.217692,129.091891,390.000000,108.184313,37.802000,-315.248833,9.692821,160.249374,170.470763,606.0,-1.302932

### **Dataset 8**: Kaggle – Top Semiconductor Companies by Market Capital

In [203]:
sc_data_df = pd.read_csv('data/raw/dataset8/sc_data.csv')
print(f"dataset shape: {sc_data_df.shape}")
sc_data_df.info()

dataset shape: (152, 6)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 152 entries, 0 to 151
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   rank                   152 non-null    int64
 1   name                   152 non-null    object
 2   ticker                 152 non-null    object
 3   market_cap_04_08_2025  152 non-null    int64
 4   price_04_08_2025       152 non-null    float64
 5   country                152 non-null    object
dtypes: float64(1), int64(2), object(3)
memory usage: 7.3+ KB

In [204]:
sc_data_clean = sc_data_df[['rank', 'name', 'ticker', 'country', 'market_cap_04_08_2025', 'price_04_08_2025']].copy()

sc_data_clean.rename(columns={
    'name': 'company',
    'market_cap_04_08_2025': 'market_cap_usd',
    'price_04_08_2025': 'stock_price_usd'
}, inplace = True)
sc_data_clean['Data_Date'] = '2025-04-08'

sc_data_clean.to_csv('data/processed/dataset8/semiconductor_companies_clean.csv', index=False)
print(f"dataset shape: {sc_data_clean.shape}")
sc_data_clean.sample(5)

dataset shape: (152, 7)

,rank,company,ticker,country,market_cap_usd,stock_price_usd,Data_Date
49,50,Lasertec,6920.T,Japan,8918025914,98.88000,2025-04-08
120,121,Alpha &amp; Omega Semiconductor,AOSL,United States,738643200,24.82000,2025-04-08
108,109,WIN Semiconductors,3105.TWO,Taiwan,1217548759,2.87198,2025-04-08
18,19,Tokyo Electron,8035.T,Japan,69418586488,151.53300,2025-04-08
61,62,HANMI Semiconductor,042700.KS,South Korea,5919532218,62.40740,2025-04-08